spring:
  application:
    name: guoshi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/user-center
  # session失效时间，一天
#  session:
#    timeout: 15s
server:
  port: 8080
  servlet:
    session:
      timeout: 15s
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭自动 驼峰转下划线/ 下划线转驼峰 ； 默认开启

# 逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)